teacher_name=input("Enter the teacher name")
subject=input("enetr the teacher name")
course_code=int(input("enter the course_code"))
name=(input("enter student name"))
age=(input("enter student age"))
usn=(input("enter student usn"))
address=(input("enter student address"))
print(f"name of student is:{name}")
print(f"age of student is:{age}")
print(f"usn of student is:{usn}")
print(f"address of student is:{address}")
print("teacher deatils:")
print("teacher name:",teacher_name)
print("Subject:",subject)
print("course code",course_code)