teacher_name=input("Enter the teacher name")
subject=input("enetr the teacher name")
course_code=int(input("enter the course_code"))
print("teacher deatils:")
print("teacher name:",teacher_name)
print("Subject:",subject)
print("course code",course_code)